/*
 * ParameterDefaults.h
 *
 */

///
///        File was automatically generated by: params_generator.py
///        Input file: gen/parameter_name.csv
///
///        Any change in file will be lost.
///

#ifndef DKMAGE_INCLUDE_DKMAGE_PARAMETERDEFAULTS_H_
#define DKMAGE_INCLUDE_DKMAGE_PARAMETERDEFAULTS_H_

/// inclusion: #include "dkmage/ParameterDefaults.h"


#define PN_DEFAULT_ACTION_POINTS_LIMIT                               "31"

#define PN_DEFAULT_SCRIPT_TUNNELLERS_LIMIT                           "256"
#define PN_DEFAULT_SCRIPT_PARTIES_LIMIT                              "256"
#define PN_DEFAULT_SCRIPT_VALUES_LIMIT                               "256"
#define PN_DEFAULT_SCRIPT_IF_CONDS_LIMIT                             "256"
#define PN_DEFAULT_SCRIPT_PARTY_DEFS_LIMIT                           "256"

#define PN_DEFAULT_GOLD_SLABS_NUMBER_CAVE                            "80"
#define PN_DEFAULT_GOLD_SLABS_NUMBER_MAZE                            "40"
#define PN_DEFAULT_GOLD_SLABS_NUMBER_HEROFORTRESS                    "52"
#define PN_DEFAULT_GEM_SLABS_NUMBER_CAVE                             "1"
#define PN_DEFAULT_GEM_SLABS_NUMBER_MAZE                             "2"
#define PN_DEFAULT_GEM_SLABS_NUMBER_HEROFORTRESS                     "1"
#define PN_DEFAULT_GEM_FACES_NUMBER_CAVE                             "1"
#define PN_DEFAULT_GEM_FACES_NUMBER_MAZE                             "2"
#define PN_DEFAULT_GEM_FACES_NUMBER_HEROFORTRESS                     "1"
#define PN_DEFAULT_GEM_TRAPS_NUMBER_CAVE                             "2"
#define PN_DEFAULT_GEM_TRAPS_NUMBER_MAZE                             "4"
#define PN_DEFAULT_GEM_TRAPS_NUMBER_HEROFORTRESS                     "2"
#define PN_DEFAULT_GEM_GUARD_NUMBER                                  "3:5"
#define PN_DEFAULT_GEM_GUARD_LEVEL                                   "4:7"
#define PN_DEFAULT_INIT_GOLD_AMOUNT                                  "20000"
#define PN_DEFAULT_CREATURES_LIMIT_CAVE                              "30"
#define PN_DEFAULT_CREATURES_LIMIT_MAZE                              "10"
#define PN_DEFAULT_CREATURES_LIMIT_HEROFORTRESS                      "25"

#define PN_DEFAULT_ENEMY_KEEPER_ATTITUDE_CAVE                        "0"
#define PN_DEFAULT_ENEMY_KEEPER_ATTITUDE_MAZE                        "0"
#define PN_DEFAULT_ENEMY_KEEPER_ROOMS_NUMBER_CAVE                    "11"
#define PN_DEFAULT_ENEMY_KEEPER_ROOMS_NUMBER_MAZE                    "11"
#define PN_DEFAULT_ENEMY_KEEPER_CREATURES_LIMIT_CAVE                 "50"
#define PN_DEFAULT_ENEMY_KEEPER_CREATURES_LIMIT_MAZE                 "50"

#define PN_DEFAULT_CENTAL_CAVERNS_NUMBER_CAVE                        "28"
#define PN_DEFAULT_CAVERN_CREATURES_NUMBER_CAVE                      "3:7"
#define PN_DEFAULT_CAVERN_CREATURES_LEVEL_CAVE                       "3:10"

#define PN_DEFAULT_ENTRANCES_NUMBER_HEROFORTRESS                     "2:5"
#define PN_DEFAULT_BRIDGE_GUARD_LEVEL_HEROFORTRESS                   "1:3"
#define PN_DEFAULT_CORRIDOR_GUARD_LEVEL_HEROFORTRESS                 "4:7"
#define PN_DEFAULT_TORTURE_GUARD_LEVEL_HEROFORTRESS                  "5:8"
#define PN_DEFAULT_GRAVEYARD_GUARD_LEVEL_HEROFORTRESS                "7:10"
#define PN_DEFAULT_DUNGEON_HEADER_GUARD_LEVEL_HEROFORTRESS           "8:10"



#endif /* DKMAGE_INCLUDE_DKMAGE_PARAMETERDEFAULTS_H_ */
