/*
 * ParameterName.h
 *
 */

///
///        File was automatically generated by: params_generator.py
///        Input file: gen/parameter_name.csv
///
///        Any change in file will be lost.
///

#ifndef DKMAGE_INCLUDE_DKMAGE_PARAMETERNAME_H_
#define DKMAGE_INCLUDE_DKMAGE_PARAMETERNAME_H_

#include <set>
#include <string>


namespace dkmage {

    /**
     *
     */
    enum class ParameterName {
        PN_CONFIG,                                /// config
        PN_DATA_PATH,                             /// data_path
        PN_LEVELS_PATH,                           /// levels_path
        PN_OUTPUT_PATH,                           /// output_path
        PN_OUTPUT_SUBPATH,                        /// output_subpath
        PN_OUTPUT_ID,                             /// output_id
        PN_OUTPUT_BMP,                            /// output_bmp

        PN_SEED,                                  /// seed
        PN_TYPE,                                  /// type

        PN_FAIL_ATTEMPTS,                         /// fail_attempts - number of failure attempts

        PN_ACTION_POINTS_LIMIT,                   /// action_points_limit

        PN_SCRIPT_TUNNELLERS_LIMIT,               /// script_tunnellers_limit
        PN_SCRIPT_PARTIES_LIMIT,                  /// script_parties_limit
        PN_SCRIPT_VALUES_LIMIT,                   /// script_values_limit
        PN_SCRIPT_IF_CONDS_LIMIT,                 /// script_if_conds_limit
        PN_SCRIPT_PARTY_DEFS_LIMIT,               /// script_party_defs_limit

        PN_GOLD_SLABS_NUMBER,                     /// gold_slabs_number
        PN_GEM_SLABS_NUMBER,                      /// gem_slabs_number
        PN_GEM_FACES_NUMBER,                      /// gem_faces_number
        PN_GEM_TRAPS_NUMBER,                      /// gem_traps_number
        PN_GEM_GUARD_NUMBER,                      /// gem_guard_number
        PN_GEM_GUARD_LEVEL,                       /// gem_guard_level
        PN_INIT_GOLD_AMOUNT,                      /// init_gold_amount
        PN_CREATURES_LIMIT,                       /// creatures_limit

        PN_ENEMY_KEEPER_ATTITUDE,                 /// enemy_keeper_attitude
        PN_ENEMY_KEEPER_ROOMS_NUMBER,             /// enemy_keeper_rooms_number
        PN_ENEMY_KEEPER_CREATURES_LIMIT,          /// enemy_keeper_creatures_limit

        PN_CENTAL_CAVERNS_NUMBER,                 /// cental_caverns_number
        PN_CAVERN_CREATURES_NUMBER,               /// cavern_creatures_number
        PN_CAVERN_CREATURES_LEVEL,                /// cavern_creatures_level

        PN_ENTRANCES_NUMBER,                      /// entrances_number
        PN_BRIDGE_GUARD_LEVEL,                    /// bridge_guard_level
        PN_CORRIDOR_GUARD_LEVEL,                  /// corridor_guard_level
        PN_TORTURE_GUARD_LEVEL,                   /// torture_guard_level
        PN_GRAVEYARD_GUARD_LEVEL,                 /// graveyard_guard_level
        PN_DUNGEON_HEADER_GUARD_LEVEL,            /// dungeon_header_guard_level

        PN_TEST_MODE,                             /// test_mode
        PN_TEST_ADDONS,                           /// test_addons
        PN_STOP_ON_FAIL                           /// stop_on_fail - do not retry generation if attempt failed
    };


    const std::set< ParameterName >& getAllParameterNames();

    /**
     * User specific parameters (e.g. paths) that does not affect map content itself.
     */
    const std::set< ParameterName >& getLocalParameterNames();

    std::string getParameterName( const ParameterName parameter );

    std::set< std::string > getParameterName( const std::set< ParameterName >& parameters );

} /* namespace dkmage */

#endif /* DKMAGE_INCLUDE_DKMAGE_PARAMETERNAME_H_ */
