##
## ParameterDefaults.cmake
##

##
##        File was automatically generated by: params_generator.py
##        Input file: gen/parameter_name.csv
##
##        Any change in file will be lost.
##


set( PN_DEFAULT_ACTION_POINTS_LIMIT                                "31" )        # action_points_limit

set( PN_DEFAULT_SCRIPT_TUNNELLERS_LIMIT                            "256" )        # script_tunnellers_limit
set( PN_DEFAULT_SCRIPT_PARTIES_LIMIT                               "256" )        # script_parties_limit
set( PN_DEFAULT_SCRIPT_VALUES_LIMIT                                "256" )        # script_values_limit
set( PN_DEFAULT_SCRIPT_IF_CONDS_LIMIT                              "256" )        # script_if_conds_limit
set( PN_DEFAULT_SCRIPT_PARTY_DEFS_LIMIT                            "256" )        # script_party_defs_limit

set( PN_DEFAULT_GOLD_SLABS_NUMBER_CAVE                             "80" )        # gold_slabs_number
set( PN_DEFAULT_GOLD_SLABS_NUMBER_MAZE                             "40" )        # gold_slabs_number
set( PN_DEFAULT_GOLD_SLABS_NUMBER_HEROFORTRESS                     "52" )        # gold_slabs_number
set( PN_DEFAULT_GEM_SLABS_NUMBER_CAVE                              "1" )        # gem_slabs_number
set( PN_DEFAULT_GEM_SLABS_NUMBER_MAZE                              "2" )        # gem_slabs_number
set( PN_DEFAULT_GEM_SLABS_NUMBER_HEROFORTRESS                      "1" )        # gem_slabs_number
set( PN_DEFAULT_GEM_FACES_NUMBER_CAVE                              "1" )        # gem_faces_number
set( PN_DEFAULT_GEM_FACES_NUMBER_MAZE                              "2" )        # gem_faces_number
set( PN_DEFAULT_GEM_FACES_NUMBER_HEROFORTRESS                      "1" )        # gem_faces_number
set( PN_DEFAULT_GEM_TRAPS_NUMBER_CAVE                              "2" )        # gem_traps_number
set( PN_DEFAULT_GEM_TRAPS_NUMBER_MAZE                              "4" )        # gem_traps_number
set( PN_DEFAULT_GEM_TRAPS_NUMBER_HEROFORTRESS                      "2" )        # gem_traps_number
set( PN_DEFAULT_GEM_GUARD_NUMBER                                   "3:5" )        # gem_guard_number
set( PN_DEFAULT_GEM_GUARD_LEVEL                                    "4:7" )        # gem_guard_level
set( PN_DEFAULT_INIT_GOLD_AMOUNT                                   "20000" )        # init_gold_amount
set( PN_DEFAULT_CREATURES_LIMIT_CAVE                               "30" )        # creatures_limit
set( PN_DEFAULT_CREATURES_LIMIT_MAZE                               "10" )        # creatures_limit
set( PN_DEFAULT_CREATURES_LIMIT_HEROFORTRESS                       "25" )        # creatures_limit

set( PN_DEFAULT_ENEMY_KEEPER_ATTITUDE_CAVE                         "0" )        # enemy_keeper_attitude
set( PN_DEFAULT_ENEMY_KEEPER_ATTITUDE_MAZE                         "0" )        # enemy_keeper_attitude
set( PN_DEFAULT_ENEMY_KEEPER_ROOMS_NUMBER_CAVE                     "11" )        # enemy_keeper_rooms_number
set( PN_DEFAULT_ENEMY_KEEPER_ROOMS_NUMBER_MAZE                     "11" )        # enemy_keeper_rooms_number
set( PN_DEFAULT_ENEMY_KEEPER_CREATURES_LIMIT_CAVE                  "50" )        # enemy_keeper_creatures_limit
set( PN_DEFAULT_ENEMY_KEEPER_CREATURES_LIMIT_MAZE                  "50" )        # enemy_keeper_creatures_limit

set( PN_DEFAULT_CENTAL_CAVERNS_NUMBER_CAVE                         "28" )        # cental_caverns_number
set( PN_DEFAULT_CAVERN_CREATURES_NUMBER_CAVE                       "3:7" )        # cavern_creatures_number
set( PN_DEFAULT_CAVERN_CREATURES_LEVEL_CAVE                        "3:10" )        # cavern_creatures_level

set( PN_DEFAULT_ENTRANCES_NUMBER_HEROFORTRESS                      "2:5" )        # entrances_number
set( PN_DEFAULT_BRIDGE_GUARD_LEVEL_HEROFORTRESS                    "1:3" )        # bridge_guard_level
set( PN_DEFAULT_CORRIDOR_GUARD_LEVEL_HEROFORTRESS                  "4:7" )        # corridor_guard_level
set( PN_DEFAULT_TORTURE_GUARD_LEVEL_HEROFORTRESS                   "5:8" )        # torture_guard_level
set( PN_DEFAULT_GRAVEYARD_GUARD_LEVEL_HEROFORTRESS                 "7:10" )        # graveyard_guard_level
set( PN_DEFAULT_DUNGEON_HEADER_GUARD_LEVEL_HEROFORTRESS            "8:10" )        # dungeon_header_guard_level

